version: '2'
services:

  php-fpm:
    build: php/
    volumes:
      - './php/php.ini:/usr/local/etc/php/php.ini'
      - './php/phperror.log:/var/log/phperror.log'
      - './php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    networks:
      - code-network

  mysql:
    hostname: db
    image: 'mariadb:10.3'
    restart: always
    volumes:
      - './mysql/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    networks:
      code-network:
        aliases:
          - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '9011:80'
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_HOST: db 
      PMA_ARBITRARY: 1
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    networks:
      - code-network

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
    networks:
      code-network:
        aliases:
          - elasticsearch
  logstash:
    build: logstash/
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
      - './logstash/lastrun:/root/.logstash_jdbc_last_run'
    ports:
      - '5001:5001'
    environment:
      LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    env_file:
      - .env
    networks:
      - code-network
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - './kibana/config/:/usr/share/kibana/config'
    ports:
      - '5601:5601'
    networks:
      - code-network
    depends_on:
      - elasticsearch
networks:
  code-network:
    driver: bridge
